# C:/Users/raysm/workspace/python/crs_dots/csrc/gp_vs_gm_game.py
# On: March 26, 2020

from dots_commands import *

set_playing("Gp,Gm")
set_play(label_name="Grampy", name="Grampy", label="Gp", playing=True, 
        position=1, color="blue", color_bg="light blue", voice=False, 
        help_play=False, pause=0.0, auto=True, level=2, steven=0.0)
set_play(label_name="Grammy", name="Grammy", label="Gm", playing=True, 
        position=2, color="red", color_bg="light yellow", voice=False, 
        help_play=False, pause=0.0, auto=True, level=2, steven=0.0)
start_game()
mark("h", 2, 5)
mark("h", 6, 4)
mark("h", 3, 6)
mark("h", 1, 1)
mark("h", 4, 2)
mark("h", 6, 2)
mark("h", 1, 6)
mark("h", 4, 4)
mark("h", 2, 2)
mark("h", 6, 3)
mark("h", 3, 5)
mark("v", 4, 1)
mark("h", 5, 6)
mark("h", 1, 3)
mark("h", 5, 5)
mark("h", 6, 5)
mark("h", 2, 1)
mark("h", 6, 1)
mark("h", 3, 3)
mark("v", 5, 6)
mark("h", 6, 6)
mark("v", 5, 5)
mark("v", 5, 7)
mark("v", 3, 1)
mark("h", 4, 3)
mark("h", 4, 1)
mark("h", 5, 1)
mark("v", 4, 2)
mark("h", 5, 2)
mark("v", 4, 3)
mark("h", 5, 3)
mark("v", 4, 4)
mark("h", 5, 4)
mark("v", 4, 5)
mark("v", 5, 4)
mark("v", 5, 3)
mark("v", 5, 2)
mark("v", 5, 1)
mark("h", 2, 4)
mark("v", 6, 1)
mark("h", 7, 1)
mark("v", 6, 2)
mark("h", 7, 2)
mark("v", 6, 3)
mark("h", 7, 3)
mark("v", 6, 4)
mark("h", 7, 4)
mark("v", 6, 5)
mark("h", 7, 5)
mark("v", 6, 6)
mark("h", 7, 6)
mark("v", 6, 7)
mark("v", 2, 1)
mark("h", 3, 1)
mark("v", 2, 2)
mark("h", 3, 2)
mark("v", 2, 3)
mark("v", 3, 2)
mark("v", 3, 3)
mark("v", 3, 4)
mark("v", 2, 4)
mark("h", 3, 4)
mark("v", 2, 5)
mark("h", 2, 3)
mark("v", 3, 5)
mark("v", 2, 6)
mark("h", 4, 5)
mark("v", 4, 6)
mark("v", 3, 6)
mark("h", 4, 6)
mark("v", 3, 7)
mark("v", 4, 7)
mark("v", 2, 7)
mark("h", 2, 6)
mark("v", 1, 7)
mark("v", 1, 6)
mark("h", 1, 5)
mark("v", 1, 5)
mark("h", 1, 4)
mark("v", 1, 4)
mark("v", 1, 3)
mark("h", 1, 2)
mark("v", 1, 2)
mark("v", 1, 1)
